server:
  port: 8088
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: zjf13760351788
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: online-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

jwt:
  # 签发人
  issuer: atxbai
  # 密钥
  secret: Zo91GApKRtonScGKhh2TEPG2Bnc9YlQrSYdFfJf3Rs85HXHXWvFIkiG6V+TKDLoJc9CipdtbBmyyOJvH9LTpig==
  # token 的过期时间 (单位：分钟) 24 * 60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值的前缀
  tokenPrefix: Bearer

