server:
  port: 8088
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5             # ??????
      maximum-pool-size: 20       # ??????
      auto-commit: true           # ????
      idle-timeout: 30000         # ????
      pool-name: online-HikariCP  # ????????
      max-lifetime: 1800000       # ??????
      connection-timeout: 30000   # ??????
      connection-test-query: SELECT 1 # ????

